info:
  title: Informazioni
  content: |-
    I nostri servizi di orientamento professionale per i/ le candidati/e al nostro progetto sono sempre gratuiti. Registrazione richiesta. Durata circa 30min.
    La pianificazione della carriera per giovani professionisti e profili junior è gratuita previa registrazione. Durata circa 50min.
    La scrittura e traduzione del curriculum vitae e la lettera di motivazione sono inclusi in tutti i nostri corsi di tedesco. I partecipanti ai corsi scrivono i propri cv e documenti sotto supervisione di un insegnante specializzata in lingua tedesca per il lavoro.
    
  list:
    - Per le traduzioni generali, si applicano i prezzi indicati.
    - Le traduzioni italiano - tedesco per alberghi e ristoranti vengono concordate dopo un primo incontro e in base alla lunghezza del testo, tipologia e difficoltà.
offers:
  - title: Consulenza gratuita per i candidati interessati ad una posizione aperta. Orientamento lavorativo per giovani professionisti/e

    subtitle:  “I sogni si realizzano, ma non senza l’aiuto degli altri, una buona istruzione, una forte etica del lavoro e una buona dose di coraggio.” - Ursula M. Burns
    courses:
      - name: |-
          Colloquio preliminare, supporto per la scrittura del CV in lingua tedesca, preparazione al colloquio, assistenza continua durante la partenza e tutta la stagione invernale.
        days: |-
          Prenota la tua consulenza gratuita scrivendo una mail a post@workitaut.at in lingua inglese o tedesca
        cost: <b> GRATUITO </b>
      - name: |-
          Pianifica la tua carriera -  primi passi nel settore alberghiero per profili entry-level e junior tra i 18 e i 26 anni
        days: |-
          Prenota la tua consulenza gratuita scrivendo una mail a post@workitaut.at in lingua inglese o tedesca
        cost: <b> GRATUITO </b>
  - title: Traduzioni Italiano - Tedesco
    subtitle:  <b>come</b> dici <b>cosa</b> a <b>chi</b> fa la differenza. Abbiamo le parole giuste per ogni obiettivo.
    courses:
      - name: |-
          Curriculum vitae efficace in tedesco
        days: |-
          Tradurre e adattare il curriculum, secondo gli standard attuali del mercato del lavoro austriaco. Adeguare il CV all'offerta di lavoro e renderlo più efficace per un colloquio lavorativo in Austria. Nel prezzo del servizio è compreso un incontro preliminare e un debriefing finale.
        cost: <del>€ 120</del> con sconto <b>€ 89</b>
      - name: |-
          Traduzione della lettera di presentazione/motivazionale
        days: |-
          Alle aziende arrivano ogni giorno centinaia di candidature, una lettera di presentazione/motivazionale è importante quanto il CV. Offriamo una traduzione che risponda alle aspettative di un madrelingua tedesco. Nel prezzo del servizio è compreso un incontro preliminare e un debriefing finale.
        cost: <del>€ 140</del> con sconto <b>€ 99</b>
      - name: |-
          Traduzioni di siti web e documenti per hotel, alberghi, ristoranti e strutture per l'ospitalità
        days: |-
          Sapersi esprimere in modo corretto in una lingua straniera è ancora oggi un punto debole per molti hotel e ristoranti. Non importa se sei il titolare di un'attività alberghiera di alto livello, un agriturismo o un piccolo B&B cittadino. Noi parliamo la lingua dei tuoi ospiti. Comunichiamo in modo efficace e corretto attraverso l’uso di un lessico adeguato al tuo target di clienti.
           Nel prezzo del servizio sono compresi una riunione preliminare, 2 incontri per revisioni e adattamenti, editing finale.
        cost: <b>Preventivo su richiesta</b>
