info:
  title: Informazioni
  content: |-
    Unsere Berufsberatung für Bewerber*innen zu unserem Projekt take some time AUT stagione invernale in Austria è sempre gratuite. Durata ca. 30min. Anmeldung erforderlich. Durata ca. 30min
    Karriereplanung für Berufseinsteiger*innen und Juniors sind nach Anmeldung gratis. Durata ca. 50min 
    Lebenslauf und Motivationschreiben werden in allen unseren Deutschkurs-Angeboten behandelt. Die Teilnehmer*innen gestalten ihre Bewerbungsunterlagen unter Anleitung selbst. 
  list:
    - Per le traduzioni generali, si applicano i prezzi indicati. 
    - Le traduzioni italiano - tedesco per alberghi e ristoranti vengono concordate dopo un primo incontro e in base al tempo e all'impegno. 
offers:
  - title: Traduzioni / italiano - tedesco
    subtitle:  Fa differenza COME dici COSA a CHI. Abbiamo le parole giuste per ogni obiettivo.
    courses:
      - name: |-
          Traduzione Curriculum ampliato
        days: |-
          Tradurre, adattare - secondo gli standard attuali e formulare per la rispettiva posizione / compreso un incontro preliminare e un debriefing.
        cost: <del>€ 120</del> con sconto € 89
    courses:
      - name: |-
          Traduzione lettera di presentazione o motivazione ampliato
        days: |-
          Tradurre, adattare - secondo gli standard attuali e formulare per la rispettiva posizione / compreso un incontro preliminare e un debriefing.
        cost: <del>€ 140</del> con sconto € 99
    courses:
      - name: |-
          Traduzione Sito di Web e materiale ristorazione per aziende alberghiere
        days: |-
          Non importa se attività alberghiera di alto livello, agriturismo ecologico o B&B cittadino. Parliamo la lingua dei tuoi ospiti. 
          Intenditori viziati, individualisti attenti alla natura, buongustai. Compreso briefing dettagliato, 2 discussioni intermedie e editing finale.
        cost: € Prezzo su richiesta
