info:
  title: Informazioni
  content: |-
    Corsi di gruppo / partecipanti min 4 max 6
    I corsi non si terranno nei giorni 8 dic; e dal 21 dic al 11 gen.
    Legenda / unità = 50min; SI = studio individuale.
    Non sono inclusi i libri da utilizzare nei corsi. Il prezzo dei libri per i corsi sarà compreso tra 17,- e 24,- euro.
  list:
    - A1 elementare, A2 pre-intermedio, B1 intermedio, B2 post-intermedio, C1 avanzato.
    - '* L´appuntamento sarà concordato con i partecipanti.'
    - '** Le date di questi giorni-extra saranno concordate con i partecipanti al gruppo.'
    - '*** Primavera sconti per tutti coloro che si iscrivono entro il 8 marzo 2021.'
offers:
  - title: Übersetzungen / Italienisch - Deutsch
    subtitle:  für Menschen, am Weg in den DACH-Raum 
    times: "hier steht vllt was"
    courses:
      - name: |-
          LEBENSLAUF ADVANCED
        days: |-
          Übersetzen, adaptieren - nach den aktuellen Standards, und formuliert für die jeweilige Stelle / inklusive eine Vorbesprechung und eine Nachbesprechung.
        cost: <del>€ 180</del> primavera sconto € 120
