info:
  title: Informazioni
  content: |-
    I nostri servizi di orientamento professionale per i/le candidati/e alle nostre posizioni aperte sono sempre gratuite. Registrazione richiesta.
    Durata circa 45min. In lingua tedesca o inglese.
    La pianificazione della carriera per giovani professionisti e profili junior è gratuita previa registrazione.
    Assistenza continua durante la partenza e tutta la stagione invernale gratuita.
  list:
    - Per le traduzioni generali, si applicano i prezzi indicati.
    - Le traduzioni italiano - tedesco per alberghi e ristoranti vengono concordate dopo un primo incontro e in base alla lunghezza del testo, tipologia e difficoltà.
offers:
  - title: Consulenza per i candidati e orientamento lavorativo per giovani professionisti/e
    subtitle: <b>Rispondiamo</b> a tutte le tue domande sulle offerte di lavoro e ti <b>sosteniamo</b> nella pianificazione del tuo futuro professionale.
    courses:
      - name: OPEN DAY in Presenza. Precolloqui per professionisti/e del settore alberghiero
        description: |-
          Presentiamo il team di Cagliari, tutte le informazioni riguardo il lavoro stagionale in Austria e le posizioni lavorative aperte. Vi sosteniamo in ogni passo: dalla candidatura fino al ritorno in
          Sardegna. Le nuove date per il mese di Novembre
          05 nov dalle 10:00 alle 11:30 (2 posti liberi)
          10 nov dalle 17:00 alle 18:30
          12 nov dalle 17:00 alle 18:30
          19 nov dalle 17:00 alle 18:30
          23 nov dalle 10:00 alle 11:30
          Luogo| Via Albert Einstein 19, Cagliari. I posti sono limitati a 6 persone a giornata. Nel rispetto delle norme anti-Covid, per la partecipazione è obbligatoria la prenotazione online.
          Non dimenticare di portare il tuo curruculm vitae!
        days: |-
          Prenota il tuo posto scrivendo a | info@dialogando.com
        cost: <b> GRATUITO</b>
      - name: Colloquio preliminare | Per i/le candidati/e ai posti di lavoro aperti
        description: Breve verifica dei documenti di candidatura | Suggerimenti per il colloquio | Domande e risposte sul luogo di lavoro, posizione e contratto.
        days: |-
          Prenota la tua consulenza gratuita su Zoom, scrivendo una mail a post@workitaut.at
        cost: <b> GRATUITO </b>
      - name: Pianifica la tua carriera | All inclusive! lavoro invernale e crescita professionale
        description: Primi passi nel settore alberghiero per profili entry-level e junior tra i 18 e i 29 anni.
        days: |-
          Prenota la tua consulenza gratuita su Zoom, scrivendo una mail a post@workitaut.at
        cost: <b> GRATUITO </b>
  - title: Traduzioni Italiano - Tedesco
    subtitle:  <b>Come</b> dici <b>cosa</b> a <b>chi</b> fa la differenza. Abbiamo le parole giuste per ogni obiettivo.
    courses:
      - name: |-
          Curriculum vitae efficace in tedesco
        description: Tradurre e adattare il curriculum, secondo gli standard attuali del mercato del lavoro austriaco. Adeguare il CV all'offerta di lavoro e renderlo più efficace per un colloquio lavorativo in Austria. Nel prezzo del servizio è compreso un incontro preliminare e un debriefing finale.
        days: |-
          Scrivendo una mail a post@workitaut.at
        cost: <del>€ 120</del> con sconto <b>€ 89</b>
      - name: |-
          Traduzione della lettera di presentazione/motivazionale
        description: Sapersi esprimere in modo corretto in una lingua straniera significa porre le basi per nuove opportunità lavorative e sentirsi al posto giusto nel momento giusto. Alle aziende arrivano ogni giorno centinaia di candidature, una lettera di presentazione/motivazionale è importante quanto il CV. Offriamo una traduzione che risponda alle aspettative di un madrelingua tedesco. Nel prezzo del servizio è compreso un incontro preliminare e un debriefing finale.
        days: |-
          Scrivendo una mail a post@workitaut.at
        cost: <del>€ 140</del> con sconto <b>€ 99</b>
      - name: |-
          Traduzione di siti web e documenti per hotel, alberghi, ristoranti e strutture per l'ospitalità
        description: Non importa se sei il titolare di un'attività alberghiera di alto livello, un agriturismo o un piccolo B&B cittadino. Noi parliamo la lingua dei tuoi ospiti. Comunichiamo in modo efficace e corretto attraverso l’uso di un lessico adeguato al tuo target di clienti. Nel prezzo del servizio sono compresi una riunione preliminare, 2 incontri per revisioni e adattamenti, editing finale.
        days: |-
          INFO post@workitaut.at
        cost: <b>Preventivo su richiesta</b>
